# Generated by Django 4.0.1 on 2022-03-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ashaworker',
            fields=[
                ('workerid', models.AutoField(primary_key=True, serialize=False)),
                ('empcode', models.CharField(max_length=100, verbose_name='empcode')),
                ('empname', models.CharField(max_length=100, verbose_name='empname')),
                ('empphoto', models.FileField(upload_to='images/', verbose_name='empphoto')),
                ('empcontact', models.CharField(max_length=100, verbose_name='empcontact')),
                ('empemail', models.CharField(max_length=100, verbose_name='empemail')),
                ('empstatus', models.CharField(max_length=100, verbose_name='empstatus')),
                ('empaddress', models.CharField(max_length=100, verbose_name='empaddress')),
            ],
        ),
        migrations.CreateModel(
            name='cases',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False)),
                ('casestatus', models.CharField(max_length=100, verbose_name='allotedate')),
                ('infectionhistory', models.CharField(max_length=100, verbose_name='allotedate')),
                ('infectiontype', models.CharField(max_length=100, verbose_name='allotedate')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100, verbose_name='location')),
                ('categorydesc', models.CharField(max_length=100, verbose_name='location')),
                ('categorytype', models.CharField(max_length=100, verbose_name='location')),
                ('categorystartdt', models.CharField(max_length=100, verbose_name='location')),
                ('categorysymtoms', models.CharField(max_length=100, verbose_name='location')),
                ('categoryprecotaions', models.CharField(max_length=100, verbose_name='location')),
                ('categorystatus', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('districtadminnm', models.CharField(max_length=100, verbose_name='admin name')),
                ('districtadmindes', models.CharField(max_length=100, verbose_name='admin designation')),
                ('districtadmindcontact', models.CharField(max_length=100, verbose_name='admin contact')),
                ('districtadmindemail', models.CharField(max_length=100, verbose_name='admin email')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='medicalshop',
            fields=[
                ('medshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=100, verbose_name='shopname')),
                ('licenseno', models.CharField(max_length=100, verbose_name='licenseno')),
                ('ownerno', models.CharField(max_length=100, verbose_name='ownerno')),
                ('contactno', models.CharField(max_length=100, verbose_name='contactno')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('workinghrs', models.CharField(max_length=100, verbose_name='workinghrs')),
                ('licensecpy', models.FileField(upload_to='images/', verbose_name='licensecpy')),
                ('medstatus', models.CharField(max_length=100, verbose_name='medstatus')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login')),
            ],
        ),
        migrations.CreateModel(
            name='servicerequest',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('isolationreason', models.CharField(max_length=100, verbose_name='isolationreason')),
                ('requirement', models.CharField(max_length=100, verbose_name='requirement')),
                ('regdate', models.CharField(max_length=100, verbose_name='regdate')),
                ('reqdate', models.CharField(max_length=100, verbose_name='reqdate')),
                ('requeststatus', models.CharField(max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district')),
                ('public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.cases')),
            ],
        ),
        migrations.CreateModel(
            name='public',
            fields=[
                ('pubid', models.AutoField(primary_key=True, serialize=False)),
                ('pubname', models.CharField(max_length=100, verbose_name='pubname')),
                ('addharno', models.CharField(max_length=100, verbose_name='addharno')),
                ('addharcopy', models.FileField(upload_to='images/', verbose_name='addharcopy')),
                ('pubdob', models.CharField(max_length=100, verbose_name='pubdob')),
                ('pubcontact', models.CharField(max_length=100, verbose_name='pubcontact')),
                ('pubemail', models.CharField(max_length=100, verbose_name='pubemail')),
                ('pubaddress', models.CharField(max_length=100, verbose_name='pubaddress')),
                ('pubjob', models.CharField(max_length=100, verbose_name='pubjob')),
                ('pubjobsector', models.CharField(max_length=100, verbose_name='pubjobsector')),
                ('pubjobdescrp', models.CharField(max_length=100, verbose_name='pubjobdescrp')),
                ('pubphoto', models.FileField(upload_to='images/', verbose_name='pubphoto')),
                ('pubstatus', models.CharField(max_length=100, verbose_name='pubstatus')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notificationtitle', models.CharField(max_length=100, verbose_name='location')),
                ('notification', models.CharField(max_length=100, verbose_name='location')),
                ('notificdate', models.CharField(max_length=100, verbose_name='location')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
            ],
        ),
        migrations.CreateModel(
            name='medicinestock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicinename', models.CharField(max_length=100, verbose_name='medicinename')),
                ('medtype', models.CharField(max_length=100, verbose_name='medtype')),
                ('medprice', models.CharField(max_length=100, verbose_name='medprice')),
                ('medqty', models.CharField(max_length=100, verbose_name='medqty')),
                ('meddec', models.CharField(max_length=100, verbose_name='meddec')),
                ('medpic', models.CharField(max_length=100, verbose_name='medpic')),
                ('medshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='kitrequest',
            fields=[
                ('kitid', models.AutoField(primary_key=True, serialize=False)),
                ('kitstaus', models.CharField(max_length=100, verbose_name='kitstaus')),
                ('requestdt', models.CharField(max_length=100, verbose_name='requestdt')),
                ('previousrequestdate', models.CharField(max_length=100, verbose_name='previousrequestdate')),
                ('alotqrcode', models.FileField(upload_to='images/', verbose_name='alotqrcode')),
                ('workstatus', models.CharField(max_length=100, verbose_name='workstatus')),
                ('allotedate', models.CharField(max_length=100, verbose_name='allotedate')),
                ('ashaworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.ashaworker')),
                ('public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doccode', models.CharField(max_length=100, verbose_name='doccode')),
                ('docname', models.CharField(max_length=100, verbose_name='docname')),
                ('docphoto', models.FileField(upload_to='images/', verbose_name='docphoto')),
                ('doccontact', models.CharField(max_length=100, verbose_name='doccontact')),
                ('docemail', models.CharField(max_length=100, verbose_name='docemail')),
                ('docstatus', models.CharField(max_length=100, verbose_name='docstatus')),
                ('docaddress', models.CharField(max_length=100, verbose_name='docaddress')),
                ('docqualification', models.CharField(max_length=100, verbose_name='docqualification')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login')),
            ],
        ),
        migrations.CreateModel(
            name='docchat',
            fields=[
                ('docchatid', models.AutoField(primary_key=True, serialize=False)),
                ('sendertype', models.CharField(max_length=100, verbose_name='sendertype')),
                ('message', models.CharField(max_length=1000, verbose_name='message')),
                ('senddate', models.CharField(max_length=100, verbose_name='senddate')),
                ('sendtime', models.CharField(max_length=100, verbose_name='sendtime')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.doctor')),
                ('public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login'),
        ),
        migrations.AddField(
            model_name='cases',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district'),
        ),
        migrations.AddField(
            model_name='cases',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public'),
        ),
        migrations.CreateModel(
            name='assisatnce',
            fields=[
                ('assitid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('cases', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.cases')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district'),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations'),
        ),
        migrations.AddField(
            model_name='ashaworker',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login'),
        ),
        migrations.CreateModel(
            name='ashachat',
            fields=[
                ('ashachatid', models.AutoField(primary_key=True, serialize=False)),
                ('sendertype', models.CharField(max_length=100, verbose_name='sendertype')),
                ('message', models.CharField(max_length=1000, verbose_name='message')),
                ('senddate', models.CharField(max_length=100, verbose_name='senddate')),
                ('sendtime', models.CharField(max_length=100, verbose_name='sendtime')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('ashaworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.ashaworker')),
                ('public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public')),
            ],
        ),
        migrations.CreateModel(
            name='allotedwork',
            fields=[
                ('allotid', models.AutoField(primary_key=True, serialize=False)),
                ('workstatus', models.CharField(max_length=100, verbose_name='workstatus')),
                ('allotedate', models.CharField(max_length=100, verbose_name='allotedate')),
                ('report', models.CharField(max_length=100, verbose_name='report')),
                ('ashaworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.ashaworker')),
                ('servicerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('alertsid', models.AutoField(primary_key=True, serialize=False)),
                ('alerttype', models.CharField(max_length=100, verbose_name='location')),
                ('alertinstrction', models.CharField(max_length=100, verbose_name='location')),
                ('postdt', models.CharField(max_length=100, verbose_name='location')),
                ('startdt', models.CharField(max_length=100, verbose_name='location')),
                ('alertstatus', models.CharField(max_length=100, verbose_name='location')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.category')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
            ],
        ),
    ]
