# Generated by Django 4.0.1 on 2022-03-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0002_category_distict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='distict',
        ),
    ]
