# Generated by Django 4.0.1 on 2022-03-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0003_remove_category_distict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district'),
        ),
    ]
