# Generated by Django 4.0.1 on 2022-03-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0004_alter_alerts_distict'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('docchatid', models.AutoField(primary_key=True, serialize=False)),
                ('workertype', models.CharField(max_length=100, verbose_name='sendertype')),
                ('sendertype', models.CharField(max_length=100, verbose_name='sendertype')),
                ('message', models.CharField(max_length=1000, verbose_name='message')),
                ('senddate', models.CharField(max_length=100, verbose_name='senddate')),
                ('sendtime', models.CharField(max_length=100, verbose_name='sendtime')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('workerid', models.AutoField(primary_key=True, serialize=False)),
                ('empcode', models.CharField(max_length=100, verbose_name='empcode')),
                ('empname', models.CharField(max_length=100, verbose_name='empname')),
                ('empphoto', models.FileField(upload_to='images/', verbose_name='empphoto')),
                ('empcontact', models.CharField(max_length=100, verbose_name='empcontact')),
                ('empemail', models.CharField(max_length=100, verbose_name='empemail')),
                ('empstatus', models.CharField(max_length=100, verbose_name='empstatus')),
                ('empaddress', models.CharField(max_length=100, verbose_name='empaddress')),
                ('emptype', models.CharField(max_length=100, verbose_name='type')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.login')),
            ],
        ),
        migrations.RemoveField(
            model_name='ashaworker',
            name='distict',
        ),
        migrations.RemoveField(
            model_name='ashaworker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ashaworker',
            name='login',
        ),
        migrations.RemoveField(
            model_name='docchat',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='docchat',
            name='public',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='distict',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='login',
        ),
        migrations.DeleteModel(
            name='ashachat',
        ),
        migrations.DeleteModel(
            name='docchat',
        ),
        migrations.AddField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.worker'),
        ),
        migrations.AddField(
            model_name='chat',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public'),
        ),
        migrations.AlterField(
            model_name='allotedwork',
            name='ashaworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.worker'),
        ),
        migrations.AlterField(
            model_name='assisatnce',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.worker'),
        ),
        migrations.AlterField(
            model_name='kitrequest',
            name='ashaworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.worker'),
        ),
        migrations.DeleteModel(
            name='ashaworker',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
