# Generated by Django 4.0.1 on 2022-03-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0005_chat_worker_remove_ashaworker_distict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalshop',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district'),
        ),
    ]
