# Generated by Django 4.0.1 on 2022-03-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0006_medicalshop_distict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.category'),
        ),
    ]
