# Generated by Django 4.0.1 on 2022-03-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0008_alter_alerts_alertinstrction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitrequest',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.district'),
        ),
    ]
