# Generated by Django 4.0.3 on 2022-03-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0009_kitrequest_distict'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.category'),
        ),
    ]
