# Generated by Django 4.0.3 on 2022-03-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0013_cases_casedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bankid', models.AutoField(primary_key=True, serialize=False)),
                ('holdername', models.CharField(max_length=100, verbose_name='holdername')),
                ('cvv', models.CharField(max_length=10, verbose_name='cvv')),
                ('accno', models.CharField(max_length=50, verbose_name='accno')),
                ('exp', models.CharField(max_length=50, verbose_name='exp')),
            ],
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='licensecpy',
            field=models.FileField(upload_to='medshop/', verbose_name='licensecpy'),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.order')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.medicinestock')),
            ],
        ),
    ]
