# Generated by Django 4.0.3 on 2022-03-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0016_servicerequest_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.public'),
        ),
    ]
