# Generated by Django 4.0.3 on 2022-04-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savekerala', '0018_alter_public_addharcopy_alter_public_pubphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savekerala.medicalshop'),
        ),
    ]
